### ISSUE TITLE
Weiterleitung evtl. besser mit rex_redirect?

### ISSUE THREAD

**Issue by skerbis** [akuehnis/redaxo5_modul_beispiele#2]
` rex_redirect($Id);`

**Comment by akuehnis** [comment]
Ist doch schon so? Oder was übersehe ich da?

**Comment by skerbis** [comment]
am Ende, letztes Modul` header("Location: REX_VALUE[1]");`

**Comment by akuehnis** [comment]
Nein, das ist nicht richtig. Die Funktion rex_redirect ist für interne Links (Argumente article_id, clang_id), beim letzen Modulbeispiel geht es jedoch um eine Weiterleitung an eine externe URL.

**Comment by skerbis** [comment]
Ups! sorry ..
